import MigrationDashboard from "@/components/MigrationDashboard";
// Generated by scripts/cleaning.py; bundled at build time so it works on GitHub Pages
import migration from "../../data/processed/vietnam_migration.json";

export default function Home() {
  const rows = migration.map(({ year, country_of_asylum_iso, refugees, asylum_seekers }) => ({
    year,
    country_of_asylum_iso,
    refugees,
    asylum_seekers,
  }));

  return (
    <main className="viz-page">
      <header>
        <h1 className="viz-h1">Vietnamese refugees and asylum-seekers in the United States and Canada</h1>
        <p className="viz-subtitle">
          People from Viet Nam that UNHCR counts as refugees or asylum-seekers in each country.
          These are population totals at year end, not yearly arrivals.
        </p>
      </header>

      <MigrationDashboard rows={rows} />

      <footer className="viz-source">
        Source: UNHCR Refugee Data Finder, persons of concern. Cleaned with{" "}
        <code>scripts/cleaning.py</code>. Canada figures start in 1994.
      </footer>
    </main>
  );
}
